import os
from building import *

# The set of source files associated with this SConscript file.
src = Split('''
string_util.cc
''') + Glob('c/*.c') + Glob('core/api/*.cc') + Glob('experimental/microfrontend/lib/*.cc') \
+ Glob('experimental/microfrontend/lib/*.c') \
+ Glob('experimental/microfrontend/lib/tools/*.c') + Glob('kernels/*.cc') + Glob('kernels/internal/*.cc') \
+ Glob('micro/*.cc') + Glob('micro/kernels/*.cc') + Glob('micro/memory_planner/*.cc') + Glob('micro/testing/*.cc')  \
+ Glob('schema/builtin_ops_header/*.cc') + Glob('micro/examples/person_detection/*.cc')

cwd = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('lite', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
