from building import *

cwd     = GetCurrentDir()
cwd = GetCurrentDir()
root =  str(Dir('#'))
packages = os.path.join(root, 'packages')
file_list = os.listdir(packages)
for f in file_list:
    if(f.split('-')[0] == 'TensorflowLiteMicro'):
        tflite = os.path.join(packages, f)
        break

CPPPATH = [cwd, tflite]

src = []

if GetDepend(['PKG_USING_TENSORFLOWLITEMICRO_AUDIO_EXAMPLE']):
    src += Split('audio_main.cc') 
else:
    src += Split('main.cc')

group = DefineGroup('lite', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
