from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cc')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('TFLMICRO_EXAMPLE', src, depend = ['BSP_USING_TFLITE_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
